### ISSUE TITLE
AI first speaking

### ISSUE THREAD

**Issue by alanzou** [twilio-samples/speech-assistant-openai-realtime-api-node#11]
This sample let the user talk first, how to let the AI to greet the user first? This is very useful for customer service agent scenario.
Thanks,

**Comment by badereddineqodia** [comment]
Right after the code sends the sessionUpdate object you can send something like this (feel free to modify the prompt):

const event = {
        type: 'conversation.item.create',
        item: {
          type: 'message',
          role: 'user',
          content: [
            {
              type: 'input_text',
              text: 'Please greet the caller and say "hi there, how can i help you?"'
            }
          ]
        }
      };
      openAiWs.send(JSON.stringify(event));
      openAiWs.send(JSON.stringify({type: 'response.create'}));

**Comment by pkamp3** [comment]
https://github.com/twilio-samples/speech-assistant-openai-realtime-api-node/issues/9#issuecomment-2406103251 hi folks, this PR would also add "AI talks first" if you'd like to take a look. 

Uncomment the `// sendInitialConversationItem();` line to test.

**Comment by HQL2024** [comment]
Excellent job! Thank you! I tried following the latest provided code and found that it is now possible to successfully interrupt OpenAI's responses. However, a problem has occurred: sometimes, when the user's background noise is relatively loud, OpenAI's voice also gets interrupted. How should we adjust it to make it adaptable to different scenarios?
