### ISSUE TITLE
Missing .env.example

### ISSUE THREAD

**Issue by fabiobarboza7** [twilio-samples/speech-assistant-openai-realtime-api-node#3]
Seems we have only the open ai key to set up, but anyways.

**Comment by fabiobarboza7** [comment]
i know, I already did. Just point to fix the readme for futher users.

**Comment by kjjd84** [comment]
I created a PR for this: https://github.com/twilio-samples/speech-assistant-openai-realtime-api-node/pull/5

hope this helps

**Comment by pkamp3** [comment]
Thanks @kjjd84 !
