### ISSUE TITLE
Feature Request: Add Support for OpenAI Azure in Real-Time API

### ISSUE THREAD

**Issue by HarounAns** [twilio-samples/speech-assistant-openai-realtime-api-node#6]
**Description:**
It would be incredibly valuable for the project to include support for OpenAI Azure's offerings in addition to the existing OpenAI API integration. Azure OpenAI Service provides the same models (e.g., GPT, Codex) but with enhanced enterprise-level security, compliance, and availability options that are crucial for businesses leveraging real-time speech recognition and generation.

**Why this is needed:**

1. **Enterprise-level security and compliance**: Many organizations require solutions that comply with stricter security and compliance regulations (e.g., GDPR, HIPAA). Azure OpenAI Service offers compliance certifications and regional availability that make it a more attractive option for enterprise users.
  
2. **Azure Infrastructure Integration**: Organizations already using Azure services may prefer to leverage their existing infrastructure and Azure's scalability, making integration smoother and more cost-effective.
  
3. **Regional Availability**: Azure OpenAI provides more control over the regions where data is processed, which can reduce latency for real-time applications like this one.

**Proposed Solution:**

1. **Configurable API Support**: Modify the codebase to allow developers to choose between OpenAI’s API and Azure OpenAI Service via environment variables or configuration settings. This would provide flexibility based on the user's preferences.

2. **Document the Setup**: Add a section to the project's README with instructions on how to configure the application for Azure OpenAI usage, including obtaining the necessary API keys, setting up the correct environment variables, and any differences in API requests or handling.

3. **Test Cases**: Implement unit tests and integration tests that ensure both OpenAI API and Azure OpenAI Service are functioning correctly in real-time usage.

**Additional Context:**

Azure OpenAI provides the same underlying models but can require different API endpoints and authentication mechanisms. Having support for this would allow users more flexibility when deploying this project in enterprise or highly regulated environments.

**Potential Challenges:**

- Handling differences in authentication (Azure AD vs. API Keys).
- Ensuring compatibility with Azure-specific API endpoints.
  
**References:**

- [Azure OpenAI Service Documentation](https://learn.microsoft.com/en-us/azure/cognitive-services/openai/)
- [OpenAI API Documentation](https://beta.openai.com/docs/)

**Comment by da1z** [comment]
Isn't azure api is fully compatible with OpenAi and you just need to change API url in the code?

**Comment by bnb** [comment]
If you'd like to see this, please feel free to submit a Pull Request with a switch - will happily review it.
