### ISSUE TITLE
Type Error in fastify package?

### ISSUE THREAD

**Issue by PhilippPreu** [twilio-samples/speech-assistant-openai-realtime-api-node#7]
I simply cloned the repo and walked through the readme. Trying to start the index.js throws this type error.

```js
speech-assistant-openai-realtime-api-node/node_modules/fastify/lib/wrapThenable.js:9
const channels = diagnostics.tracingChannel('fastify.request.handler')
                             ^

TypeError: diagnostics.tracingChannel is not a function
    at Object.<anonymous> (/.../speech-assistant-openai-realtime-api-node/node_modules/fastify/lib/wrapThenable.js:9:30)
```

**Comment by pkamp3** [comment]
Which version of Node are you using @PhilippPreu ? v18.20.4 is what we used to build it.

**Comment by badereddineqodia** [comment]
i think you have an issue with your Node vesion

**Comment by blrobin2** [comment]
I encountered the same issue — I am running Node.js v18.18.2

**Comment by coinspiracynut** [comment]
I have the same error on node 19.2.0

**Comment by bnb** [comment]
If anyone has a fix and would like to make it work in newer versions, please feel free to PR.
